name: progression_tree_map
description: This is  a visual representation tool that helps users track and understand the development or growth of a process or a concept.
version: 1.3.5
homepage: https://github.com/Frankline-Sable/progression_tree_map

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  vector_math: ^2.1.4
  collection: ^1.19.1
  interactive_viewer_2: ^0.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:

